[package]
name = "and-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["host"] }
tracing-subscriber = "0.3"
tracing = "0.1"
guest = { package = "and-chain-guest", path = "./guest" }
